# Generated by Django 5.1.1 on 2025-03-31 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0003_delete_usuario_alter_profile_user'),
        ('app_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_creadas', to='app_usuarios.profile'),
        ),
    ]
