# Generated by Django 5.1.1 on 2025-03-31 03:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_pedidos', '0001_initial'),
        ('app_ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido', 'Pedido'), ('personalizado', 'Personalizado')], default='pedido', max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(default='Pedido', max_length=100)),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egreso', to='app_pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2)])),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2)])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ingreso', to='app_ventas.venta')),
            ],
            options={
                'unique_together': {('venta',)},
            },
        ),
    ]
