# Generated by Django 5.1.1 on 2025-03-31 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finanzas', '0001_initial'),
        ('app_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingreso',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='tipo',
            field=models.CharField(choices=[('venta', 'Venta'), ('personalizado', 'Personalizado')], default='venta', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ventas.venta'),
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='subtotal',
        ),
    ]
