# Generated by Django 5.1.1 on 2025-04-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finanzas', '0002_alter_ingreso_unique_together_ingreso_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='ingreso',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
