# Generated by Django 5.1.1 on 2025-04-01 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_finanzas', '0003_alter_ingreso_options_ingreso_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='subtotal',
        ),
    ]
