# Generated by Django 5.1.1 on 2025-04-01 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_finanzas', '0004_remove_ingreso_subtotal'),
    ]

    operations = [
    ]
