# Generated by Django 5.1.1 on 2025-04-01 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedidos', '0002_alter_proveedor_options_proveedor_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetalle',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_pedidos.pedido'),
        ),
    ]
